fullnameOverride: svc-orders
nameOverride: svc-orders
image:
  repository: ghcr.io/jagadeesh-ml/svc-orders
  tag: "sha-70f32940f4495f758e2e440f4246ffdbaff9d086"
replicaCount: 1
service:
  port: 80
  targetPort: 8080
