fullnameOverride: svc-orders

image:
  repository: ghcr.io/jagadeesh-ml/svc-orders
  tag: "sha-03ce01b8550e8644bc61d11ebf5edd9d0fd63998"

replicaCount: 2

service:
  port: 80
  targetPort: 8080

# Uncomment only if you want to force amd64 nodes temporarily
# nodeSelector:
#   kubernetes.io/arch: amd64
