image:
  repository: ghcr.io/jagadeesh-ml/svc-orders
  tag: "sha-03ce01b8550e8644bc61d11ebf5edd9d0fd63998"

replicaCount: 2

service:
  port: 80
  targetPort: 8080

# If your cluster is mixed arch and image is multi-arch, you can omit this.
# If you ever need to force amd64 only, uncomment:
# nodeSelector:
#   kubernetes.io/arch: amd64
