apiVersion: v1
kind: Service
metadata:
  name: {{ default .Chart.Name .Values.nameOverride }}
  labels:
    app: {{ default .Chart.Name .Values.nameOverride }}
spec:
  selector:
    app: {{ default .Chart.Name .Values.nameOverride }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      protocol: TCP
