image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-65cfc2c7ad3551ad10f3afdd60d78a5f55233b99"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
