image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-6ecabadb7a97e760874a7508c757560a7a0d3e55"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
