image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-1076b74a7cfcd2aeb1a11bc357b8a7c57886ce74"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
