image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-333ffd0ed8734d517985026b66213d360d68dc0d"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
