image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-fefe23172d69e1f0326c6e388238627585846a47"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
