image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-4cb0bd3db14501be9209122a44f8390f4a685dbf"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
