image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-79fd464a79e0b3e0ce696275d45f752e5121eb09"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
