image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-60fb85453244097a096dae6ccdcbad46051752de"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
