image:
  repository: ghcr.io/jagadeesh-ml/svc-users
  tag: "sha-531e6cabadc374de06c6b9e115065d723934a36d"
  pullPolicy: IfNotPresent
service:
  port: 80
  targetPort: 8080
replicaCount: 2
nameOverride: svc-users
